title: Yo-Docs
description: The Yo-Kai Watch documentation site.
remote_theme: just-the-docs/just-the-docs

color_scheme: dark

baseurl: "/yo-docs"
url: "https://ykw-modding.github.io"

aux_links:
  The Yo-Kai Watch Modding Discord: https://discord.gg/TbmKf6Ujq3

aux_links_new_tab: true

nav_sort: case_sensitive
